export const actions = {
    "FETCH_ALL": "FETCH_ALL",
    "CREATE_MOMENT": "CREATE_MOMENT",
    "UPDATE_MOMENT": "UPDATE_MOMENT",
    "DELETE_MOMENT": "DELETE_MOMENT",
    "AUTHENTICATION": "AUTHENTICATION",
    "LOGOUT": "LOGOUT",
    "ERROR": "ERROR",
    "CREATE_COMMENT": "CREATE_COMMENT",
};
